Fix: 500 internal error returned for some users
beaker-project/beaker pull request #87
Opened 2021-02-04 19:08 UTC by cbouchar

When getting users from beaker by way of
https:/beaker.com/users/username and that user is retired from company,
seeing a "500 internal error" instead of "Not Found" error.  The
failure is in get user LDAP look-up since an exception is raised when
looking for the "mail" key entry that no longer exists. Code
now checks whether it is present. If not, None returned for user.

Closes: BKR-5058

2021-02-08 09:05 UTC, renanrodrigo commented
Checked the failing test and it's actually passing - small bug on the report side.

2021-02-08 09:08 UTC, StykMartin commented
Why this maintenance work is aiming to "develop" again? This should be in release-28 branch.

2021-02-08 09:09 UTC, StykMartin requested changes
`develop` -> `release-28`

2021-02-08 11:26 UTC, cbouchar commented
> Checked the failing test and it's actually passing - small bug on the report side.

For the life of me I can't see what teh issue is.  Could you point me to the file in particular where the error is seen?

2021-02-08 11:27 UTC, cbouchar commented
> `develop` -> `release-28`

Yes I made a mistake.  I'll resubmit once I find where in the needlestack the error is reported.

2021-02-15 12:45 UTC, cbouchar commented
This changeset is closed as discussed with the user.

2021-02-15 12:45 UTC, closed without merging